### PR TITLE
renamed resources to paarse vrijdag

### PR DESCRIPTION
**Pull request by laurensWe**

### CODE REVIEW

**Comment by thomcsmits** [comment]
There has been a request to split dwhdelft.nl/resources into 
dwhdelft.nl/purplefriday
dwhdelft.nl/resources
dwhdelft.nl/supporter

I am still waiting on the content for each though, but until then I wouldn't just change the name

**Comment by casperboone** [comment]
The URL is also only flyers and stuff, if we change something here it needs some redirects at least :)

**Review by casperboone — CHANGES_REQUESTED** [review]
(requesting a change to remove this from my list of open review requests)

**Comment by laurensWe** [comment]
Hehe so much for requesting 😅

**Comment by laurensWe** [comment]
Closing because someone else will fix this :)

**Pull request closed without merging**
