### PR TITLE
fix: update outsite hours

### PR DESCRIPTION
**Pull request by thomcsmits**

### CODE REVIEW

**Review by laurensWe — APPROVED** [review]
LGTM

**Comment by casperboone** [comment]
Don’t forget to PR this to the Nuxt 3 branch as well

**Comment by casperboone** [comment]
I think the end time moves back to 1:00 as well

**Comment by thomcsmits** [comment]
> Don’t forget to PR this to the Nuxt 3 branch as well
Goeie! Added in #571 

> I think the end time moves back to 1:00 as well

Vgm doen we daar nog steeds niets mee, maar idd wel veranderd.

**Pull request merged**
